### ISSUE TITLE
recase with redmine 1.4

### ISSUE THREAD

**Issue by myersware** [cforce/redcase_branch#1]
I tried installing it with redmine 1.4 and migration gives this error:  
uninitialized constant ApplicationHelper::GravatarHelper

**Comment by daest** [comment]
I have a similar problem with redmine 1.4.1. After installing the plugin, it's listed in the plugin section of redmines administrator view.
By activating the plugin (checkbox in the setting/info/trackers/testcase), redmine throws an internal error if I try to access the project.

**Comment by daest** [comment]
Here the log:

ActionView::TemplateError (No route matches {:controller=>"redcase", :project_id=>#<Project id: 11, name: "Sandbox", description: "Playing area for people which would become project ...", homepage: "", is_public: true, parent_id: nil, created_on: "2012-03-29 14:34:44", updated_on: "2012-03-29 14:34:44", identifier: "sandbox", status: 1, lft: 19, rgt: 22, dmsf_description: nil>, :action=>"index"}) on line #57 of app/views/layouts/base.html.erb:
54: 
55:     <% if display_main_menu?(@project) %>
56:     <div id="main-menu">
57:         <%= render_main_menu(@project) %>
58:     </div>
59:     <% end %>
60: </div>

```
lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
lib/redmine/menu_manager.rb:102:in `render_menu_node'
lib/redmine/menu_manager.rb:91:in `render_menu'
lib/redmine/menu_manager.rb:168:in `menu_items_for'
lib/redmine/menu_manager.rb:165:in `each'
lib/redmine/menu_manager.rb:165:in `menu_items_for'
lib/redmine/menu_manager.rb:90:in `render_menu'
lib/redmine/menu_manager.rb:80:in `render_main_menu'
app/views/layouts/base.html.erb:57
app/controllers/projects_controller.rb:168:in `show'
config/initializers/mongrel.rb:123:in `dispatch_cgi'
```

Rendering C:/homepage/joomla/redmine/public/500.html (500 Internal Server Error)

**Comment by cforce** [comment]
For redmine 1.4 a routes.rb is needed. We still use redmine 1.3 and don't need that at the moment.

**Comment by errantpixel** [comment]
Has anyone been able to create a working routes.rb for this branch (or any) of redcase? 

I feel like I'm peeling an onion here.
